-- Pharmacy Analytics (Part 1)
-- Calculate the total profit generated by each drug.
-- Return the top 3 drugs with the highest total profit.

SELECT
    drug,
    (total_sales - cogs) AS total_profit
FROM pharmacy_sales
GROUP BY
    drug,
    (total_sales - cogs)
ORDER BY total_profit DESC
LIMIT 3